services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: csyt-image
    container_name: csyt-app
    restart: always
    env_file:
      - .env
    ports:
      - "8080:${SERVER_PORT}"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: csyt_user
      DATABASE_PASSWORD: 123456
    depends_on:
      mysql:
        condition: service_healthy
      # 2. Dịch vụ Database
  mysql:
    image: mysql:8.0
    container_name: csyt-db
    restart: always
    environment:
      MYSQL_DATABASE: donation
      MYSQL_USER: csyt_user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 1234567
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - '3307:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234567" ]
      interval: 5s       # Kiểm tra mỗi 5 giây
      timeout: 5s        # Chờ tối đa 5 giây cho mỗi lần kiểm tra
      retries: 10        # Thử lại 10 lần trước khi báo lỗi
      start_period: 10s  # Chờ 10s trước khi bắt đầu kiểm tra lần đầu (để DB kịp khởi tạo)
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake

# Định nghĩa volume (nơi lưu trữ dữ liệu DB)
volumes:
  mysql_data: