server:
  port: ${SERVER_PORT:8080}
app:
  base-url: ${APP_BASE_URL:http://localhost:${SERVER_PORT:8080}}
  token:
    expiry-minutes: 10

upload:
  path: uploads/thumbnails/

spring:
  application:
    name: DonationManagement
  datasource:
    url:
      ${MYSQL_URL:jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/donation?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

#PayOS
payos:
  client-id: 02745e9c-7c5a-4a1e-81d0-bb50281bec1f
  api-key: a189d0aa-4443-4b62-b1ff-ae64b057a0eb
  checksum-key: 5304c2338d683c8eb7d9734b2ccdecb52016e029d464946f11b8a653971eefc1
  return-url: ${app.base-url}/thanh-toan/thanh-cong
  cancel-url: ${app.base-url}/thanh-toan/that-bai

